
---

## 1. Иерархия встроенных типов в Python

### Задание 1
Построение и визуализация иерархической модели встроенных типов объектов Python.

Ниже представлена иерархическая модель встроенных типов Python с указанием:
- примера литерала для создания объекта
- упорядоченности элементов (для коллекций)
- изменяемости/неизменяемости объектов

```
                        Встроенные типы Python
                                │
        ┌───────────────────────┼───────────────────────┐
        │                       │                       │
    Числовые               Коллекции                 Прочие
        │                       │                       │
   ┌────┼────┐         ┌────────┼────────┐         ┌────┼────┐
   │    │    │         │        │        │         │    │    │
  int float complex  Последов. Отображ. Множеств. bool None type
  42  3.14 2+3j       │      dict     │        True None type(x)
  неизм неизм неизм   │    {'a':1}    │        неизм
                       │    изменяем  set frozenset
               ┌───────┼──────┐   {1,2}  frozenset({1})
               │       │      │   изменяем неизменяем
              str    list   tuple
             'abc'  [1,2]  (1,2)
           упоряд  упоряд  упоряд
           неизм   изменяем неизм
```

**Пояснения:**
- **Упорядоченные коллекции** (сохраняют порядок): `str`, `list`, `tuple`; `dict` (с Python 3.7+ сохраняет порядок вставки)
- **Неупорядоченные коллекции**: `set`, `frozenset`
- **Изменяемые (mutable)**: `list`, `dict`, `set`
- **Неизменяемые (immutable)**: `int`, `float`, `complex`, `str`, `tuple`, `frozenset`, `bool`, `NoneType`


---
## 2. Проработка примеров из лекционного материала

### Задание 2.1 — Информационная структура лекций


### 2.1. Объект как фундаментальное понятие в Python
### 2.2. Встроенные типы числовых объектов: int, float, complex
### 2.3. Встроенные типы последовательностей: str, list, tuple
### 2.4. Встроенный тип отображения: dict
### 2.5. Встроенный тип множества: set
### 2.6. Встроенный тип логического объекта: bool
### 2.7. Специальный объект None
### 2.8. Интерфейс объекта: операции и методы
### 2.9. Переменная
### 2.10. Включения (comprehensions)
### 2.11. Форматированный вывод строк
### 2.12. Файловый объект


---
### Задание 2.2 — Выполнение упражнений по разделам

---
#### Раздел 2.3. Встроенные типы последовательностей: str, list, tuple

**Задача:** Определить строку `S = 'spam'`. Написать выражение, которое изменяет строку на `'slam'`, используя нарезание и конкатенацию. Рассмотреть также индексацию, присваивание по индексу. Привести аналогичные примеры для списка и кортежа.


In [1]:
# Исходная строка
S = 'spam'
print(f"Исходная строка: {S}")

# Способ 1: нарезание (slicing) + конкатенация
S_new = S[0] + 'l' + S[2:]
print(f"Нарезание + конкатенация: {S_new}")

# Способ 2: индексация + конкатенация
S_new2 = S[0] + 'l' + S[2] + S[3]
print(f"Индексация + конкатенация: {S_new2}")

# Способ 3: попытка присваивания по индексу (ОШИБКА — строки неизменяемы)
try:
    S[1] = 'l'
except TypeError as e:
    print(f"Присваивание по индексу для строки: ошибка — {e}")


Исходная строка: spam
Нарезание + конкатенация: slam
Индексация + конкатенация: slam
Присваивание по индексу для строки: ошибка — 'str' object does not support item assignment


In [2]:
# Аналогичные операции для списка
L = ['s', 'p', 'a', 'm']
print(f"Исходный список: {L}")

# Список — изменяемый объект, поэтому можно присваивать по индексу
L[1] = 'l'
print(f"Присваивание по индексу: {L}")

# Через нарезание + конкатенацию (создаёт НОВЫЙ список)
L2 = ['s', 'p', 'a', 'm']
L2_new = L2[:1] + ['l'] + L2[2:]
print(f"Нарезание + конкатенация: {L2_new}")
print(f"Объекты разные? id(L2)={id(L2)}, id(L2_new)={id(L2_new)}")


Исходный список: ['s', 'p', 'a', 'm']
Присваивание по индексу: ['s', 'l', 'a', 'm']
Нарезание + конкатенация: ['s', 'l', 'a', 'm']
Объекты разные? id(L2)=139469268240576, id(L2_new)=139469268252928


In [3]:
# Аналогичные операции для кортежа
T = ('s', 'p', 'a', 'm')
print(f"Исходный кортеж: {T}")

# Кортеж — неизменяемый, как и строка. Используем нарезание + конкатенацию
T_new = T[:1] + ('l',) + T[2:]
print(f"Нарезание + конкатенация: {T_new}")

# Попытка присваивания по индексу — ошибка
try:
    T[1] = 'l'
except TypeError as e:
    print(f"Присваивание по индексу для кортежа: ошибка — {e}")

# Вывод: и строки, и кортежи неизменяемы — для модификации нужно создавать новый объект


Исходный кортеж: ('s', 'p', 'a', 'm')
Нарезание + конкатенация: ('s', 'l', 'a', 'm')
Присваивание по индексу для кортежа: ошибка — 'tuple' object does not support item assignment


---
#### Раздел 2.4. Встроенный тип отображения: dict

**Задача:** Создать структуру данных, представляющую персональную информацию, используя различные комбинации встроенных типов.


In [4]:
# Вариант 1: словарь (наиболее осмысленная структура — ключи описывают семантику)
person = {
    'имя': {
        'имя': 'Александр',
        'отчество': 'Иванович',
        'фамилия': 'Петров'
    },
    'возраст': 21,
    'место_работы': 'БГУ, ММФ, студент',
    'адрес': 'г. Минск, ул. Академическая, д. 15, кв. 42',
    'email': 'petrov_ai@mail.ru',
    'телефон': '+375291234567'
}

# Доступ к компонентам
print("Фамилия:", person['имя']['фамилия'])
print("Возраст:", person['возраст'])
print("Email:", person['email'])


Фамилия: Петров
Возраст: 21
Email: petrov_ai@mail.ru


In [5]:
# Вариант 2: вложенный список кортежей
person_list = [
    ('имя', ('Александр', 'Иванович', 'Петров')),
    ('возраст', 21),
    ('место_работы', 'БГУ, ММФ, студент'),
    ('адрес', 'г. Минск, ул. Академическая, д. 15, кв. 42'),
    ('email', 'petrov_ai@mail.ru'),
    ('телефон', '+375291234567')
]

# Доступ по индексу — менее удобный, чем по ключу
print("Имя полностью:", person_list[0][1])
print("Место работы:", person_list[2][1])

# Вывод: словарь наиболее осмыслен, так как ключи несут семантическую нагрузку,
# а доступ к полям осуществляется по имени, а не по числовому индексу.


Имя полностью: ('Александр', 'Иванович', 'Петров')
Место работы: БГУ, ММФ, студент


---
#### Раздел 2.5. Встроенный тип множества: set

**Задача:** Удаление повторяющихся символов строки с использованием множества.


In [6]:
# Удаление повторяющихся символов строки
original = 'абракадабра'
print(f"Исходная строка: '{original}'")

# Преобразуем строку в множество — автоматически удаляются дубликаты
unique_chars = set(original)
print(f"Уникальные символы (множество): {unique_chars}")

# Если нужно получить строку обратно (порядок может измениться!)
unique_str = ''.join(sorted(unique_chars))
print(f"Строка из уникальных символов (отсортированная): '{unique_str}'")

# Ещё пример — английский текст
text = 'mississippi'
print(f"\n'{text}' -> уникальные символы: {set(text)}")
print(f"Количество уникальных символов: {len(set(text))}")


Исходная строка: 'абракадабра'
Уникальные символы (множество): {'р', 'а', 'д', 'б', 'к'}
Строка из уникальных символов (отсортированная): 'абдкр'

'mississippi' -> уникальные символы: {'m', 'p', 's', 'i'}
Количество уникальных символов: 4


---
#### Раздел 2.8. Интерфейс объекта: операции и методы

**Задача 1:** Соединение списка строк в одну строку (join) и разбиение строки на список подстрок (split).


In [7]:
# Метод str.join(iterable) — соединяет элементы iterable через строку-разделитель
# Спецификация: S.join(iterable) -> str
# Возвращает строку, полученную конкатенацией элементов iterable через S

words = ['Python', 'это', 'мощный', 'язык']
separator = ' '
result = separator.join(words)
print(f"Список: {words}")
print(f"Результат join(' '): '{result}'")

# Соединение через дефис
result2 = '-'.join(['2026', '03', '13'])
print(f"Через дефис: '{result2}'")


Список: ['Python', 'это', 'мощный', 'язык']
Результат join(' '): 'Python это мощный язык'
Через дефис: '2026-03-13'


In [8]:
# Метод str.split(sep=None, maxsplit=-1) -> list[str]
# Спецификация: разбивает строку по разделителю sep, возвращает список подстрок
# Если sep=None, разбиение по пробельным символам

sentence = 'Python это мощный язык'
parts = sentence.split(' ')
print(f"Строка: '{sentence}'")
print(f"Результат split(' '): {parts}")

# Разбиение по запятой
csv_line = 'Минск,Гомель,Брест,Витебск'
cities = csv_line.split(',')
print(f"\nCSV: '{csv_line}'")
print(f"Результат split(','): {cities}")


Строка: 'Python это мощный язык'
Результат split(' '): ['Python', 'это', 'мощный', 'язык']

CSV: 'Минск,Гомель,Брест,Витебск'
Результат split(','): ['Минск', 'Гомель', 'Брест', 'Витебск']


**Задача 2:** Три способа добавления элемента в список.

In [9]:
# Способ 1: метод append — добавляет один элемент в конец
lst = [1, 2, 3]
lst.append(4)
print(f"append(4): {lst}")

# Способ 2: метод insert — вставляет элемент по заданному индексу
lst2 = [1, 2, 3]
lst2.insert(1, 99)  # вставить 99 на позицию 1
print(f"insert(1, 99): {lst2}")

# Способ 3: метод extend — добавляет все элементы итерируемого объекта
lst3 = [1, 2, 3]
lst3.extend([4, 5])
print(f"extend([4, 5]): {lst3}")

# Бонус: через конкатенацию (создаёт новый объект, а не модифицирует)
lst4 = [1, 2, 3]
lst4 = lst4 + [4]
print(f"Конкатенация + [4]: {lst4}")


append(4): [1, 2, 3, 4]
insert(1, 99): [1, 99, 2, 3]
extend([4, 5]): [1, 2, 3, 4, 5]
Конкатенация + [4]: [1, 2, 3, 4]


**Задача 3:** Перестановка элементов в обратном порядке (операция и метод). Аналогия для строки и кортежа.

In [10]:
# Список: метод reverse() — модифицирует на месте (in-place)
lst = [10, 20, 30, 40, 50]
print(f"Исходный список: {lst}")
lst.reverse()
print(f"После reverse(): {lst}")

# Список: операция нарезания [::-1] — создаёт новый перевёрнутый список
lst2 = [10, 20, 30, 40, 50]
lst2_rev = lst2[::-1]
print(f"Через [::-1]: {lst2_rev} (оригинал: {lst2})")


Исходный список: [10, 20, 30, 40, 50]
После reverse(): [50, 40, 30, 20, 10]
Через [::-1]: [50, 40, 30, 20, 10] (оригинал: [10, 20, 30, 40, 50])


In [11]:
# Строка — неизменяемая, метод reverse() отсутствует
s = 'Привет'
# s.reverse()  # AttributeError — у строки нет метода reverse
s_rev = s[::-1]
print(f"Строка '{s}' в обратном порядке: '{s_rev}'")

# Кортеж — неизменяемый, метод reverse() отсутствует
t = (1, 2, 3, 4, 5)
# t.reverse()  # AttributeError — у кортежа нет метода reverse
t_rev = t[::-1]
print(f"Кортеж {t} в обратном порядке: {t_rev}")

# Вывод: для неизменяемых типов (str, tuple) используется только нарезание [::-1],
# которое создаёт новый объект. Метод reverse() доступен только для списков.


Строка 'Привет' в обратном порядке: 'тевирП'
Кортеж (1, 2, 3, 4, 5) в обратном порядке: (5, 4, 3, 2, 1)


**Задача 4:** Сортировка списка с аргументом key.

In [12]:
# Сортировка с параметром key
# Метод list.sort(key=None, reverse=False) — сортирует список на месте

words = ['банан', 'Яблоко', 'вишня', 'Арбуз', 'груша']
print(f"До сортировки: {words}")

# Сортировка по умолчанию — с учётом регистра (заглавные буквы идут первыми)
words_copy = words.copy()
words_copy.sort()
print(f"sort() по умолчанию: {words_copy}")

# Сортировка без учёта регистра — key=str.lower
words.sort(key=str.lower)
print(f"sort(key=str.lower): {words}")

# Сортировка по длине слова
data = ['кот', 'медведь', 'лев', 'жираф', 'волк']
data.sort(key=len)
print(f"\nСортировка по длине: {data}")

# Комментарий: параметр key задаёт функцию, результат которой используется
# для сравнения элементов. Сами элементы при этом не изменяются.


До сортировки: ['банан', 'Яблоко', 'вишня', 'Арбуз', 'груша']
sort() по умолчанию: ['Арбуз', 'Яблоко', 'банан', 'вишня', 'груша']
sort(key=str.lower): ['Арбуз', 'банан', 'вишня', 'груша', 'Яблоко']

Сортировка по длине: ['кот', 'лев', 'волк', 'жираф', 'медведь']


---
#### Раздел 2.9. Переменная

**Задача 1:** Циклические (рекурсивные) объекты для различных встроенных типов.


In [13]:
# Циклический список — элемент списка ссылается на сам список
cyclic_list = [1, 2, 3]
cyclic_list.append(cyclic_list)
print(f"Циклический список: {cyclic_list}")
# Python выводит [...] для обозначения цикла

# Проверим: последний элемент IS сам список
print(f"cyclic_list[3] is cyclic_list: {cyclic_list[3] is cyclic_list}")


Циклический список: [1, 2, 3, [...]]
cyclic_list[3] is cyclic_list: True


In [14]:
# Циклический словарь
cyclic_dict = {'ключ': 'значение'}
cyclic_dict['self'] = cyclic_dict
print(f"Циклический словарь: {cyclic_dict}")

# Вложенный цикл в множестве невозможен напрямую:
# set не может содержать изменяемые объекты (они нехешируемы)
try:
    s = {1, 2}
    s.add(s)
except TypeError as e:
    print(f"Множество не поддерживает вложение в себя: {e}")


Циклический словарь: {'ключ': 'значение', 'self': {...}}
Множество не поддерживает вложение в себя: unhashable type: 'set'


**Задача 2:** Объект с четырьмя ссылками. Подсчёт количества ссылок.

In [15]:
import sys

# Создаём объект и четыре ссылки на него
original = [100, 200, 300]
ref_a = original
ref_b = original
ref_c = original

# Все переменные ссылаются на один и тот же объект
print(f"id(original) = {id(original)}")
print(f"id(ref_a)    = {id(ref_a)}")
print(f"id(ref_b)    = {id(ref_b)}")
print(f"id(ref_c)    = {id(ref_c)}")

# Количество ссылок на объект
# sys.getrefcount() добавляет +1 за саму передачу аргумента
ref_count = sys.getrefcount(original)
print(f"\nsys.getrefcount(original) = {ref_count}")
print(f"Реальное количество ссылок ≈ {ref_count} (включая временную ссылку getrefcount)")


id(original) = 139469266341888
id(ref_a)    = 139469266341888
id(ref_b)    = 139469266341888
id(ref_c)    = 139469266341888

sys.getrefcount(original) = 5
Реальное количество ссылок ≈ 5 (включая временную ссылку getrefcount)


**Задача 3:** Четыре способа копирования элементов списка. Отличие copy от deepcopy.

In [16]:
import copy

# Исходный список (содержит вложенный список)
original = [[1, 2], [3, 4], 'текст']

# Способ 1: метод copy()
copy1 = original.copy()

# Способ 2: нарезание [:]
copy2 = original[:]

# Способ 3: конструктор list()
copy3 = list(original)

# Способ 4: copy.copy() (поверхностная копия)
copy4 = copy.copy(original)

print("Все 4 способа создают поверхностные копии:")
print(f"original:      {original}")
print(f"copy1 (.copy): {copy1}")
print(f"copy2 ([:]   ): {copy2}")
print(f"copy3 (list()): {copy3}")
print(f"copy4 (copy.copy): {copy4}")


Все 4 способа создают поверхностные копии:
original:      [[1, 2], [3, 4], 'текст']
copy1 (.copy): [[1, 2], [3, 4], 'текст']
copy2 ([:]   ): [[1, 2], [3, 4], 'текст']
copy3 (list()): [[1, 2], [3, 4], 'текст']
copy4 (copy.copy): [[1, 2], [3, 4], 'текст']


In [17]:
import copy

# Демонстрация отличия поверхностной копии (copy) от глубокой (deepcopy)
original = [[1, 2, 3], [4, 5, 6]]

shallow = original.copy()       # поверхностная копия
deep = copy.deepcopy(original)  # глубокая копия

# Модифицируем вложенный список оригинала
original[0][0] = 999

print(f"original после изменения: {original}")
print(f"shallow (поверхностная):  {shallow}")   # ИЗМЕНИЛСЯ! [0][0] == 999
print(f"deep (глубокая):          {deep}")       # НЕ изменился! [0][0] == 1

# Пояснение: поверхностная копия (copy) создаёт новый внешний список,
# но вложенные объекты НЕ копируются — они разделяются между оригиналом и копией.
# Глубокая копия (deepcopy) рекурсивно копирует ВСЕ вложенные объекты.
print(f"\nshallow[0] is original[0]: {shallow[0] is original[0]}")  # True
print(f"deep[0] is original[0]:    {deep[0] is original[0]}")      # False


original после изменения: [[999, 2, 3], [4, 5, 6]]
shallow (поверхностная):  [[999, 2, 3], [4, 5, 6]]
deep (глубокая):          [[1, 2, 3], [4, 5, 6]]

shallow[0] is original[0]: True
deep[0] is original[0]:    False


---
#### Раздел 2.10. Включения (comprehensions)

**Задача 1:** Создание множества с использованием включения с условием.


In [18]:
# Множество чётных квадратов чисел от 1 до 20
even_squares = {x**2 for x in range(1, 21) if x % 2 == 0}
print(f"Чётные квадраты (1..20): {even_squares}")

# Множество гласных букв в тексте
text = 'Компьютерная математика и системный анализ'
vowels = {'а', 'е', 'ё', 'и', 'о', 'у', 'ы', 'э', 'ю', 'я'}
found_vowels = {ch.lower() for ch in text if ch.lower() in vowels}
print(f"Гласные в тексте: {found_vowels}")


Чётные квадраты (1..20): {64, 256, 100, 4, 36, 196, 324, 16, 144, 400}
Гласные в тексте: {'ы', 'я', 'е', 'о', 'а', 'и', 'ю'}


**Задача 2:** Числовая матрица 7×8 через вложенные включения и через numpy.

In [19]:
# Матрица 7x8 через вложенные включения: элемент = i * 8 + j + 1
matrix = [[i * 8 + j + 1 for j in range(8)] for i in range(7)]
print("Матрица 7×8 (list comprehension):")
for row in matrix:
    print(row)


Матрица 7×8 (list comprehension):
[1, 2, 3, 4, 5, 6, 7, 8]
[9, 10, 11, 12, 13, 14, 15, 16]
[17, 18, 19, 20, 21, 22, 23, 24]
[25, 26, 27, 28, 29, 30, 31, 32]
[33, 34, 35, 36, 37, 38, 39, 40]
[41, 42, 43, 44, 45, 46, 47, 48]
[49, 50, 51, 52, 53, 54, 55, 56]


In [20]:
import numpy as np

# Аналогичная матрица через numpy
matrix_np = np.arange(1, 57).reshape(7, 8)
print("Матрица 7×8 (numpy):")
print(matrix_np)
print(f"\nТип: {type(matrix_np)}, размерность: {matrix_np.shape}")


Матрица 7×8 (numpy):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]]

Тип: <class 'numpy.ndarray'>, размерность: (7, 8)


**Задача 3:** Словарь с включением и двумя уровнями вложенности.

In [21]:
# Словарь: для каждой буквы — вложенный словарь с кодами символов
# Пример с двумя уровнями вложенности
alphabet_info = {
    letter: {f'код_{enc}': letter.encode(enc) for enc in ['utf-8', 'ascii']}
    for letter in 'ABCDEF'
}
print("Словарь с двумя уровнями вложенности:")
for key, val in alphabet_info.items():
    print(f"  {key}: {val}")

# Ещё пример: таблица умножения как словарь словарей
mult_table = {
    i: {j: i * j for j in range(1, 4)}
    for i in range(1, 4)
}
print(f"\nТаблица умножения: {mult_table}")
print(f"3 × 2 = {mult_table[3][2]}")


Словарь с двумя уровнями вложенности:
  A: {'код_utf-8': b'A', 'код_ascii': b'A'}
  B: {'код_utf-8': b'B', 'код_ascii': b'B'}
  C: {'код_utf-8': b'C', 'код_ascii': b'C'}
  D: {'код_utf-8': b'D', 'код_ascii': b'D'}
  E: {'код_utf-8': b'E', 'код_ascii': b'E'}
  F: {'код_utf-8': b'F', 'код_ascii': b'F'}

Таблица умножения: {1: {1: 1, 2: 2, 3: 3}, 2: {1: 2, 2: 4, 3: 6}, 3: {1: 3, 2: 6, 3: 9}}
3 × 2 = 6


---
#### Раздел 2.11. Форматированный вывод строк

**Задача 1:** Форматирование переменной через f-string `{variable=:…}`, оператор `%` и метод `format`.


In [22]:
# Переменная для форматирования
pi = 3.141592653589793

# Способ 1: f-строка с синтаксисом variable=
print(f"{pi=:.4f}")
# Выводит: pi=3.1416 — отладочный формат, показывает имя переменной и значение

# Способ 2: бинарная операция %
print("pi=%.4f" % pi)

# Способ 3: метод format
print("pi={:.4f}".format(pi))


pi=3.1416
pi=3.1416
pi=3.1416


**Задача 2:** Форматирование выражения через f-string `{expression=:…}`, оператор `%` и метод `format`.

In [23]:
x = 7
y = 3

# Способ 1: f-строка с выражением
print(f"{x + y=:>10d}")
# Показывает выражение и его результат с выравниванием вправо в поле шириной 10

# Способ 2: бинарная операция %
print("x + y=%10d" % (x + y))

# Способ 3: метод format
print("x + y={:>10d}".format(x + y))


x + y=        10
x + y=        10
x + y=        10


---
#### Раздел 2.12. Файловый объект

**Задача:** Примеры использования функций и методов: `open`, `close`, `read`, `readline`, `readlines`, `write`, `writelines`.


In [24]:
# Запись в файл: open, write, writelines, close
f = open('example.txt', 'w', encoding='utf-8')
f.write('Первая строка файла\n')            # write — записывает строку
f.write('Вторая строка файла\n')
f.writelines(['Третья строка\n',            # writelines — записывает список строк
              'Четвёртая строка\n',
              'Пятая строка\n'])
f.close()                                    # close — закрывает файл
print("Файл записан успешно.")


Файл записан успешно.


In [25]:
# Чтение файла целиком: read
f = open('example.txt', 'r', encoding='utf-8')
content = f.read()           # read — читает весь файл как одну строку
f.close()
print("read() — весь файл:")
print(content)


read() — весь файл:
Первая строка файла
Вторая строка файла
Третья строка
Четвёртая строка
Пятая строка



In [26]:
# Чтение построчно: readline
f = open('example.txt', 'r', encoding='utf-8')
line1 = f.readline()         # readline — читает одну строку
line2 = f.readline()
f.close()
print(f"readline() 1: {line1!r}")
print(f"readline() 2: {line2!r}")


readline() 1: 'Первая строка файла\n'
readline() 2: 'Вторая строка файла\n'


In [27]:
# Чтение всех строк в список: readlines
f = open('example.txt', 'r', encoding='utf-8')
lines = f.readlines()        # readlines — возвращает список всех строк
f.close()
print(f"readlines(): {lines}")
print(f"Количество строк: {len(lines)}")

# Рекомендуемый способ — менеджер контекста (автоматически закрывает файл)
with open('example.txt', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f, 1):
        print(f"Строка {i}: {line.strip()}")


readlines(): ['Первая строка файла\n', 'Вторая строка файла\n', 'Третья строка\n', 'Четвёртая строка\n', 'Пятая строка\n']
Количество строк: 5
Строка 1: Первая строка файла
Строка 2: Вторая строка файла
Строка 3: Третья строка
Строка 4: Четвёртая строка
Строка 5: Пятая строка


---
### Задание 2.3 — Фрагменты кода с ошибками

Ниже приведены типичные ошибки при работе со встроенными типами Python (на основе лекционного материала), их причины и исправления.


**Ошибка 1:** Попытка изменить символ строки по индексу (строки неизменяемы)

In [28]:
# Ошибочный код:
s = 'hello'
try:
    s[0] = 'H'
except TypeError as e:
    print(f"Ошибка: {e}")
    # Причина: строка — неизменяемый (immutable) объект

# Исправление: создать новую строку
s = 'H' + s[1:]
print(f"Исправлено: {s}")


Ошибка: 'str' object does not support item assignment
Исправлено: Hello


**Ошибка 2:** Обращение к несуществующему ключу словаря

In [29]:
# Ошибочный код:
d = {'a': 1, 'b': 2}
try:
    val = d['c']
except KeyError as e:
    print(f"Ошибка: KeyError — ключ {e} не найден в словаре")
    # Причина: ключ 'c' отсутствует в словаре

# Исправление: использовать метод get с значением по умолчанию
val = d.get('c', 0)
print(f"Исправлено (get): {val}")


Ошибка: KeyError — ключ 'c' не найден в словаре
Исправлено (get): 0


**Ошибка 3:** Попытка сложить строку и число

In [30]:
# Ошибочный код:
try:
    result = 'возраст: ' + 21
except TypeError as e:
    print(f"Ошибка: {e}")
    # Причина: Python не выполняет неявное преобразование int к str

# Исправление: явное преобразование
result = 'возраст: ' + str(21)
print(f"Исправлено: {result}")


Ошибка: can only concatenate str (not "int") to str
Исправлено: возраст: 21


**Ошибка 4:** Выход за пределы индекса списка

In [31]:
# Ошибочный код:
lst = [10, 20, 30]
try:
    print(lst[5])
except IndexError as e:
    print(f"Ошибка: {e}")
    # Причина: индекс 5 выходит за пределы списка длиной 3

# Исправление: проверить длину или использовать допустимый индекс
print(f"Исправлено: lst[-1] = {lst[-1]}")


Ошибка: list index out of range
Исправлено: lst[-1] = 30


**Ошибка 5:** Добавление изменяемого элемента (списка) в множество

In [32]:
# Ошибочный код:
try:
    s = {1, 2, [3, 4]}
except TypeError as e:
    print(f"Ошибка: {e}")
    # Причина: список — нехешируемый (unhashable) объект,
    # а множество может содержать только хешируемые элементы

# Исправление: использовать кортеж вместо списка
s = {1, 2, (3, 4)}
print(f"Исправлено (кортеж): {s}")


Ошибка: unhashable type: 'list'
Исправлено (кортеж): {1, 2, (3, 4)}


**Ошибка 6:** Модификация словаря при итерации

In [33]:
# Ошибочный код:
d = {'a': 1, 'b': 2, 'c': 3}
try:
    for key in d:
        if d[key] < 2:
            del d[key]
except RuntimeError as e:
    print(f"Ошибка: {e}")
    # Причина: нельзя изменять размер словаря во время итерации по нему

# Исправление: итерировать по копии ключей
d = {'a': 1, 'b': 2, 'c': 3}
for key in list(d.keys()):
    if d[key] < 2:
        del d[key]
print(f"Исправлено: {d}")


Ошибка: dictionary changed size during iteration
Исправлено: {'b': 2, 'c': 3}


**Ошибка 7:** Попытка вызвать метод sort у кортежа

In [34]:
# Ошибочный код:
t = (5, 2, 8, 1)
try:
    t.sort()
except AttributeError as e:
    print(f"Ошибка: {e}")
    # Причина: кортеж — неизменяемый, метод sort() отсутствует

# Исправление: использовать встроенную функцию sorted()
t_sorted = tuple(sorted(t))
print(f"Исправлено: {t_sorted}")


Ошибка: 'tuple' object has no attribute 'sort'
Исправлено: (1, 2, 5, 8)


**Ошибка 8:** Деление на ноль

In [35]:
# Ошибочный код:
try:
    x = 10 / 0
except ZeroDivisionError as e:
    print(f"Ошибка: {e}")
    # Причина: деление на ноль математически не определено

# Исправление: проверка делителя
divisor = 0
x = 10 / divisor if divisor != 0 else float('inf')
print(f"Исправлено: {x}")


Ошибка: division by zero
Исправлено: inf


**Ошибка 9:** Использование изменяемого объекта как значения по умолчанию

In [36]:
# Ошибочный код:
def add_item_bad(item, lst=[]):
    lst.append(item)
    return lst

# При повторных вызовах список «накапливается» — неожиданное поведение
print(add_item_bad(1))  # [1]
print(add_item_bad(2))  # [1, 2] — ожидалось [2]!
# Причина: аргумент по умолчанию создаётся один раз при определении функции

# Исправление: использовать None как значение по умолчанию
def add_item_good(item, lst=None):
    if lst is None:
        lst = []
    lst.append(item)
    return lst

print(add_item_good(1))  # [1]
print(add_item_good(2))  # [2] — правильно


[1]
[1, 2]
[1]
[2]


---
### Задание 2.4 — Рекомендация из PEP 8

**Рекомендация:** *Используйте 4 пробела для каждого уровня отступа.* Не используйте символы табуляции для создания отступов. Пробелы являются предпочтительным способом создания отступов в Python.

Эта рекомендация критически важна, поскольку в Python отступы определяют структуру блоков кода (в отличие от фигурных скобок в C/C++/Java).


In [37]:
# Пример кода, соответствующего PEP 8 (4 пробела на уровень):

def calculate_statistics(numbers):
    """Вычисляет базовые статистики для списка чисел."""
    if not numbers:
        return None

    total = sum(numbers)
    count = len(numbers)
    mean = total / count

    sorted_nums = sorted(numbers)
    mid = count // 2
    if count % 2 == 0:
        median = (sorted_nums[mid - 1] + sorted_nums[mid]) / 2
    else:
        median = sorted_nums[mid]

    return {'среднее': mean, 'медиана': median, 'сумма': total}


data = [15, 8, 23, 42, 4, 16]
stats = calculate_statistics(data)
print(f"Данные: {data}")
print(f"Статистика: {stats}")

# Каждый уровень вложенности (def, if, else) добавляет ровно 4 пробела


Данные: [15, 8, 23, 42, 4, 16]
Статистика: {'среднее': 18.0, 'медиана': 15.5, 'сумма': 108}


---
## 3. Ответы на контрольные вопросы (Лутц, часть II, главы 4–9)

### Глава 4. Введение в типы объектов Python

**Вопрос:** Назовите основные встроенные типы объектов Python.

**Ответ:** Основные встроенные типы объектов Python: числа (`int`, `float`, `complex`), строки (`str`), списки (`list`), кортежи (`tuple`), словари (`dict`), множества (`set`, `frozenset`), логический тип (`bool`), специальный объект `None`, а также файловые объекты. Каждый тип имеет свой набор операций и методов.


In [38]:
# Иллюстрация: основные типы и их литералы
examples = {
    'int': 42,
    'float': 3.14,
    'complex': 2 + 3j,
    'str': 'hello',
    'list': [1, 2, 3],
    'tuple': (1, 2, 3),
    'dict': {'a': 1},
    'set': {1, 2, 3},
    'bool': True,
    'NoneType': None,
}

for name, obj in examples.items():
    print(f"{name:>10}: {str(obj):>15}  ->  type = {type(obj).__name__}")


       int:              42  ->  type = int
     float:            3.14  ->  type = float
   complex:          (2+3j)  ->  type = complex
       str:           hello  ->  type = str
      list:       [1, 2, 3]  ->  type = list
     tuple:       (1, 2, 3)  ->  type = tuple
      dict:        {'a': 1}  ->  type = dict
       set:       {1, 2, 3}  ->  type = set
      bool:            True  ->  type = bool
  NoneType:            None  ->  type = NoneType


---
### Глава 5. Числовые типы

**Вопрос:** Чем отличается целочисленное деление `//` от обычного деления `/` в Python 3?

**Ответ:** Оператор `/` всегда возвращает результат типа `float`, даже если оба операнда целые. Оператор `//` выполняет деление с округлением вниз (к отрицательной бесконечности) и возвращает целое число, если оба операнда целые.


In [39]:
# Разница между / и //
print(f"7 / 2 = {7 / 2}")       # 3.5 (float)
print(f"7 // 2 = {7 // 2}")     # 3 (int, округление вниз)
print(f"-7 // 2 = {-7 // 2}")   # -4 (округление к -∞, а не к нулю!)
print(f"7.0 // 2 = {7.0 // 2}") # 3.0 (float, т.к. один из операндов — float)

# divmod возвращает пару (частное, остаток)
print(f"divmod(7, 2) = {divmod(7, 2)}")


7 / 2 = 3.5
7 // 2 = 3
-7 // 2 = -4
7.0 // 2 = 3.0
divmod(7, 2) = (3, 1)


---
### Глава 6. Строки

**Вопрос:** Что такое нарезание (slicing) строк и как оно работает?

**Ответ:** Нарезание — это извлечение подстроки с использованием синтаксиса `S[start:end:step]`, где `start` — начальный индекс (включительно), `end` — конечный (исключительно), `step` — шаг. Все параметры необязательны, по умолчанию: `start=0`, `end=len(S)`, `step=1`.


In [40]:
S = 'Лабораторная работа'
print(f"Строка: '{S}'")
print(f"S[0:12]:    '{S[0:12]}'")    # первые 12 символов
print(f"S[13:]:     '{S[13:]}'")     # с 13-го до конца
print(f"S[::2]:     '{S[::2]}'")     # каждый второй символ
print(f"S[::-1]:    '{S[::-1]}'")    # строка в обратном порядке
print(f"S[-6:]:     '{S[-6:]}'")     # последние 6 символов


Строка: 'Лабораторная работа'


S[0:12]:    'Лабораторная'
S[13:]:     'работа'
S[::2]:     'Лбртра аоа'
S[::-1]:    'атобар яанротаробаЛ'
S[-6:]:     'работа'


---
### Глава 7. Списки и словари

**Вопрос:** В чём ключевое отличие списка от словаря?

**Ответ:** Список — упорядоченная коллекция элементов с доступом по числовому индексу (позиции). Словарь — коллекция пар «ключ-значение» с доступом по произвольному неизменяемому ключу. Списки оптимальны для упорядоченных наборов данных, словари — для ассоциативных данных, где важно быстрое обращение по ключу.


In [41]:
# Список: доступ по позиции
colors = ['красный', 'зелёный', 'синий']
print(f"Список: colors[1] = '{colors[1]}'")

# Словарь: доступ по ключу
rgb = {'красный': '#FF0000', 'зелёный': '#00FF00', 'синий': '#0000FF'}
print(f"Словарь: rgb['зелёный'] = '{rgb['зелёный']}'")

# Словарь позволяет быстрый поиск O(1), список — O(n) для поиска по значению
print(f"'зелёный' in rgb: {('зелёный' in rgb)}")   # O(1)
print(f"'зелёный' in colors: {('зелёный' in colors)}")  # O(n)


Список: colors[1] = 'зелёный'
Словарь: rgb['зелёный'] = '#00FF00'
'зелёный' in rgb: True
'зелёный' in colors: True


---
### Глава 8. Кортежи и файлы

**Вопрос:** Зачем нужны кортежи, если есть списки?

**Ответ:** Кортежи неизменяемы, что даёт несколько преимуществ: они могут использоваться как ключи словаря и элементы множества; обеспечивают целостность данных (защиту от случайного изменения); занимают меньше памяти и работают быстрее списков. Кортежи уместны для фиксированных наборов данных, таких как координаты или записи из базы данных.


In [42]:
import sys

# Кортеж как ключ словаря (список не может быть ключом!)
locations = {
    (53.9, 27.57): 'Минск',
    (55.75, 37.62): 'Москва'
}
print(f"Координаты Минска: {locations[(53.9, 27.57)]}")

# Сравнение размера в памяти
lst = [1, 2, 3, 4, 5]
tpl = (1, 2, 3, 4, 5)
print(f"\nРазмер списка [1..5]: {sys.getsizeof(lst)} байт")
print(f"Размер кортежа (1..5): {sys.getsizeof(tpl)} байт")
# Кортеж обычно занимает меньше памяти


Координаты Минска: Минск

Размер списка [1..5]: 104 байт
Размер кортежа (1..5): 80 байт


---
### Глава 9. Общий обзор объектов

**Вопрос:** Что такое полиморфизм в контексте операций Python?

**Ответ:** Полиморфизм означает, что одна и та же операция (например, `+`, `len()`, итерация) может применяться к объектам разных типов, и результат зависит от типа операнда. Это позволяет писать универсальный код, который работает с разными типами данных.


In [43]:
# Оператор + — полиморфный: конкатенация для строк/списков, сложение для чисел
print(f"3 + 4       = {3 + 4}")                    # сложение
print(f"'ab' + 'cd' = {'ab' + 'cd'}")              # конкатенация строк
print(f"[1,2] + [3] = {[1,2] + [3]}")              # конкатенация списков

# Функция len() — работает для любых коллекций
print(f"\nlen('hello')    = {len('hello')}")
print(f"len([1,2,3])    = {len([1,2,3])}")
print(f"len({{'a':1}})    = {len({'a':1})}")

# Оператор * — повторение для последовательностей, умножение для чисел
print(f"\n'ab' * 3    = {'ab' * 3}")
print(f"[0] * 5     = {[0] * 5}")
print(f"3 * 4       = {3 * 4}")


3 + 4       = 7
'ab' + 'cd' = abcd
[1,2] + [3] = [1, 2, 3]

len('hello')    = 5
len([1,2,3])    = 3
len({'a':1})    = 1

'ab' * 3    = ababab
[0] * 5     = [0, 0, 0, 0, 0]
3 * 4       = 12


---
## Заключение

В ходе лабораторной работы были изучены:
- иерархия встроенных типов Python и их свойства (изменяемость, упорядоченность);
- операции и методы для работы со строками, списками, кортежами, словарями и множествами;
- механизм переменных и ссылок, поверхностное и глубокое копирование;
- генераторы включений (comprehensions) для создания коллекций;
- форматированный вывод строк (f-строки, %, format);
- работа с файловыми объектами;
- принципы полиморфизма встроенных операций Python.
